package main

import (
	"summer-internship/TOPIC_10_ALGORITHMS_FOR_PROCESS_SYMBOL_INFO"
	"summer-internship/TOPIC_1_LINEAR_ALGORITHMS"
	"summer-internship/TOPIC_2_BRANCHING_ALGORITHMS"
	"summer-internship/TOPIC_3_CYCLIC_AND_ITERATIVE_ALGORITHMS"
	"summer-internship/TOPIC_4_THE_SIMPLE_OPERATIONS_ON_ARRAYS"
	"summer-internship/TOPIC_5_VECTORS_AND_MATRICES"
	"summer-internship/TOPIC_6_LINEAR_SEARCH"
	"summer-internship/TOPIC_7_ARITHMETIC"
	"summer-internship/TOPIC_8_GEOMETRY_AND_SET_THEORY"
	"summer-internship/TOPIC_9_LINEAR_ALGEB_AND_INFO_COMPRESS"
)

func main() {
	//Запуск выполненных задачек на golang:
	TOPIC_1_LINEAR_ALGORITHMS.Main1()
	TOPIC_2_BRANCHING_ALGORITHMS.Main2()
	TOPIC_3_CYCLIC_AND_ITERATIVE_ALGORITHMS.Main3()
	TOPIC_4_THE_SIMPLE_OPERATIONS_ON_ARRAYS.Main4()
	TOPIC_5_VECTORS_AND_MATRICES.Main5()
	TOPIC_6_LINEAR_SEARCH.Main6()
	TOPIC_7_ARITHMETIC.Main7()
	TOPIC_8_GEOMETRY_AND_SET_THEORY.Main8()
	TOPIC_9_LINEAR_ALGEB_AND_INFO_COMPRESS.Main9()
	TOPIC_10_ALGORITHMS_FOR_PROCESS_SYMBOL_INFO.Main10()
}
